# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('movies_name1', models.CharField(max_length=160)),
                ('movies_link1', models.URLField()),
                ('movies_name2', models.CharField(max_length=160)),
                ('movies_link2', models.URLField()),
                ('movies_name3', models.CharField(max_length=160)),
                ('movies_link3', models.URLField()),
                ('movies_name4', models.CharField(max_length=160)),
                ('movies_link4', models.URLField()),
                ('movies_name5', models.CharField(max_length=160)),
                ('movies_link5', models.URLField()),
                ('books_name1', models.CharField(max_length=160)),
                ('books_link1', models.URLField()),
                ('books_name2', models.CharField(max_length=160)),
                ('books_link2', models.URLField()),
                ('books_name3', models.CharField(max_length=160)),
                ('books_link3', models.URLField()),
                ('books_name4', models.CharField(max_length=160)),
                ('books_link4', models.URLField()),
                ('books_name5', models.CharField(max_length=160)),
                ('books_link5', models.URLField()),
                ('songs_name1', models.CharField(max_length=160)),
                ('songs_link1', models.URLField()),
                ('songs_name2', models.CharField(max_length=160)),
                ('songs_link2', models.URLField()),
                ('songs_name3', models.CharField(max_length=160)),
                ('songs_link3', models.URLField()),
                ('songs_name4', models.CharField(max_length=160)),
                ('songs_link4', models.URLField()),
                ('songs_name5', models.CharField(max_length=160)),
                ('songs_link5', models.URLField()),
                ('series_name1', models.CharField(max_length=160)),
                ('series_link1', models.URLField()),
                ('series_name2', models.CharField(max_length=160)),
                ('series_link2', models.URLField()),
                ('series_name3', models.CharField(max_length=160)),
                ('series_link3', models.URLField()),
                ('series_name4', models.CharField(max_length=160)),
                ('series_link4', models.URLField()),
                ('series_name5', models.CharField(max_length=160)),
                ('series_link5', models.URLField()),
            ],
        ),
    ]
