# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20160717_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='books_link1',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='books_link2',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='books_link3',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='books_link4',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='books_link5',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='books_name1',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='books_name2',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='books_name3',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='books_name4',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='books_name5',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='movies_link1',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='movies_link2',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='movies_link3',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='movies_link4',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='movies_link5',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='movies_name1',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='movies_name2',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='movies_name3',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='movies_name4',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='movies_name5',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='series_link1',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='series_link2',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='series_link3',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='series_link4',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='series_link5',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='series_name1',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='series_name2',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='series_name3',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='series_name4',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='series_name5',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='songs_link1',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='songs_link2',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='songs_link3',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='songs_link4',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='songs_link5',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='songs_name1',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='songs_name2',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='songs_name3',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='songs_name4',
            field=models.CharField(default='name', max_length=160),
        ),
        migrations.AddField(
            model_name='result',
            name='songs_name5',
            field=models.CharField(default='name', max_length=160),
        ),
    ]
