# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20160801_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='books_audible1',
            field=models.URLField(default='http://www.audible.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='books_audible2',
            field=models.URLField(default='http://www.audible.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='books_audible3',
            field=models.URLField(default='http://www.audible.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='books_audible4',
            field=models.URLField(default='http://www.audible.com'),
        ),
        migrations.AddField(
            model_name='result',
            name='books_audible5',
            field=models.URLField(default='http://www.audible.com'),
        ),
    ]
